on:
  push:
    paths:
      - '**.lua' # Run if pushed commits include a change to a Lua (.lua) file.
      - 'extension.xml' # Run if pushed commits include a change to extension.xml.
      - '.github/workflows/luacheck.yml' # Run if pushed commits change this workflow.
  pull_request:
    paths:
      - '**.lua' # Run if pull request includes a change to a Lua (.lua) file.
      - 'extension.xml' # Run if pull request includes a change to extension.xml.
  workflow_dispatch:

name: Run Stylua

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            version: v2.0.2
            args: --check .
